//
//  KLBNotifications.m
//  Battle of Blades
//
//  Created by Chase Gosingtian on 8/29/14.
//  Copyright (c) 2014 KLab Cyscorpions, Inc. All rights reserved.
//

#import "KLBNotifications.h"

NSString *const KLB_NOTIFICATION_BATTLE_START_ATTEMPT = @"KLB_NOTIFICATION_BATTLE_START_ATTEMPT";
NSString *const KLB_NOTIFICATION_BATTLE_START = @"KLB_NOTIFICATION_BATTLE_START";
NSString *const KLB_NOTIFICATION_BATTLE_END = @"KLB_NOTIFICATION_BATTLE_END";
NSString *const KLB_NOTIFICATION_PLAYER_NAME_CHANGED = @"KLB_NOTIFICATION_PLAYER_NAME_CHANGED";
NSString *const KLB_NOTIFICATION_PLAYER_LEVEL_CHANGED = @"KLB_NOTIFICATION_PLAYER_LEVEL_CHANGED";
NSString *const KLB_NOTIFICATION_PLAYER_EXPERIENCE_CHANGED = @"KLB_NOTIFICATION_PLAYER_EXPERIENCE_CHANGED";
NSString *const KLB_NOTIFICATION_PLAYER_ENERGY_CHANGED = @"KLB_NOTIFICATION_PLAYER_ENERGY_CHANGED";

@implementation KLBNotifications

@end
