//
//  KLBNotifications.m
//  Battle of Blades
//
//  Created by Chase Gosingtian on 8/29/14.
//  Copyright (c) 2014 KLab Cyscorpions, Inc. All rights reserved.
//

#import "KLBNotifications.h"

NSString *const KLB_NOTIFICATION_BATTLE_START_ATTEMPT = @"KLB_NOTIFICATION_BATTLE_START_ATTEMPT";
NSString *const KLB_NOTIFICATION_BATTLE_START = @"KLB_NOTIFICATION_BATTLE_START";
NSString *const KLB_NOTIFICATION_BATTLE_END = @"KLB_NOTIFICATION_BATTLE_END";
NSString *const KLB_NOTIFICATION_PLAYER_NAME_CHANGED = @"KLB_NOTIFICATION_PLAYER_NAME_CHANGED";
NSString *const KLB_NOTIFICATION_PLAYER_LEVEL_CHANGED = @"KLB_NOTIFICATION_PLAYER_LEVEL_CHANGED";
NSString *const KLB_NOTIFICATION_PLAYER_EXPERIENCE_CHANGED = @"KLB_NOTIFICATION_PLAYER_EXPERIENCE_CHANGED";
NSString *const KLB_NOTIFICATION_PLAYER_ENERGY_CHANGED = @"KLB_NOTIFICATION_PLAYER_ENERGY_CHANGED";
NSString *const KLB_NOTIFICATION_ENEMY_TIME_OVER = @"KLB_NOTIFICATION_ENEMY_TIME_OVER";
NSString *const KLB_NOTIFICATION_ENEMY_HEALTH_ZERO = @"KLB_NOTIFICATION_ENEMY_HEALTH_ZERO";
NSString *const KLB_NOTIFICATION_ENEMY_NAME_CHANGED = @"KLB_NOTIFICATION_ENEMY_NAME_CHANGED";
NSString *const KLB_NOTIFICATION_ENEMY_LEVEL_CHANGED = @"KLB_NOTIFICATION_ENEMY_LEVEL_CHANGED";
NSString *const KLB_NOTIFICATION_ENEMY_HEALTH_CHANGED = @"KLB_NOTIFICATION_ENEMY_HEALTH_CHANGED";
NSString *const KLB_NOTIFICATION_ENEMY_TIME_CHANGED = @"KLB_NOTIFICATION_ENEMY_TIME_CHANGED";
NSString *const KLB_NOTIFICATION_ENEMY_BLOCK_APPLIED = @"KLB_NOTIFICATION_ENEMY_BLOCK_APPLIED";
NSString *const KLB_NOTIFICATION_ATTACK_SUCCESS = @"KLB_NOTIFICATION_ATTACK_SUCCESS";
NSString *const KLB_NOTIFICATION_BLOCK_SUCCESS = @"KLB_NOTIFICATION_BLOCK_SUCCESS";
NSString *const KLB_NOTIFICATION_BUTTON_SPAWN_START = @"KLB_NOTIFICATION_BUTTON_SPAWN_START";
NSString *const KLB_NOTIFICATION_CHEAT_CLEAR_SHIELDS = @"KLB_NOTIFICATION_CHEAT_CLEAR_SHIELDS";
NSString *const KLB_NOTIFICATION_CHEAT_GAIN_LEVEL = @"KLB_NOTIFICATION_CHEAT_GAIN_LEVEL";

@implementation KLBNotifications

@end
